Repository Moumita-08/Hacktoberfest, pull requests merged in 2022-10, with the labels that each got.

#2 1st commit merging and bubble sort
  merge.c
Labels: good first issue, Hacktoberfest2022, Hacktoberfest

#16 Frequency Of String Done
  Frequency of String.cpp
Labels: good first issue, Hacktoberfest2022, Hacktoberfest, Hacktoberfest-accepted

#19 Sparsa matrix, commited
  sparse_matrix.c
Labels: enhancement, good first issue, Hacktoberfest2022, Hacktoberfest, Hacktoberfest-accepted

#21 String initial _ 1 commit ahead
  String_initial.c
Labels: documentation, enhancement, good first issue, question, Hacktoberfest2022, Hacktoberfest, Hacktoberfest-accepted
